# -*- coding: utf-8 -*-
"""YOLOv4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_eV9MA1E0z-e4dqubj-O8N-BtO5L-ZQ
"""

!git clone https://github.com/AlexeyAB/darknet

from google.colab import drive
drive.mount('/content/drive')

!unzip -uq "/content/drive/My Drive/Dataset.zip" -d "/content/darknet"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet/

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile
!sed -i 's/LIBSO=0/LIBSO=1/' Makefile

!make

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

!./darknet detector train cfg/obj.data cfg/yolov4-custom.cfg yolov4.conv.137 -dont_show -map

!./darknet detector train cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_last.weights -dont_show -map

!./darknet detector train cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_last.weights -dont_show -map

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 196.jpg

import cv2
import matplotlib.pyplot as plt
import os.path

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 209.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 001047.png

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 732.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 885.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights pic1.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 001299.png

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov4-custom.cfg /content/drive/MyDrive/yolov4-custom_best.weights 151.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)