# -*- coding: utf-8 -*-
"""YOLOv3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y8XggM2ZPmar3t3_c3sORwqvCayWg4ud
"""

!git clone https://github.com/AlexeyAB/darknet.git

# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

!unzip -uq "/content/drive/My Drive/Dataset.zip" -d "/content/darknet"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet/

!sed -i 's/GPU=0/GPU=1/g' Makefile

!make

!wget https://pjreddie.com/media/files/darknet53.conv.74

import glob
import os

# Current directory
current_dir = '/content/darknet/Dataset'

# Percentage of images to be used for the test set
percentage_test = 10;

# Create and/or truncate train.txt and test.txt
file_train = open('train.txt', 'w')
file_test = open('test.txt', 'w')

# Populate train.txt and test.txt
counter = 1
index_test = round(100 / percentage_test)
for pathAndFilename in glob.iglob(os.path.join(current_dir, "*.png")):
    title, ext = os.path.splitext(os.path.basename(pathAndFilename))
    if counter == index_test:
        counter = 1
        file_test.write(current_dir + "/" + title + '.png' + "\n")
    else:
        file_train.write(current_dir + "/" + title + '.png' + "\n")
        counter = counter + 1

!./darknet detector train cfg/obj.data cfg/yolov3.cfg darknet53.conv.74

!./darknet detector train cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights

!./darknet detector train cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights

!./darknet detector train cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights 196.jpg

import cv2
import matplotlib.pyplot as plt
import os.path

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights 209.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights 001047.png

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights 001077.png

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights 732.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights 238.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights pic1.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights pic164.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)

!./darknet detector test cfg/obj.data cfg/yolov3.cfg /content/drive/MyDrive/yolov3_last.weights pic169.jpg

fig,ax = plt.subplots()
ax.tick_params(labelbottom="off",bottom="off")
ax.tick_params(labelleft="off",left="off")
ax.set_xticklabels([]) 
ax.axis('off')

file = '/content/darknet/predictions.jpg'
if os.path.exists(file):
  img = cv2.imread(file)
  show_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
  plt.imshow(show_img)